### PR TITLE
Updated css danny pages

### PR DESCRIPTION
**Pull request by DannyENL**
Updated my pages to include css

### CODE REVIEW

**Review by ProtoRedux — CHANGES_REQUESTED** [review]
your computer_misuse.html file has no changes only an update to the name.
Could you check this and let me know?

**Comment by DannyENL** [comment]
Computer misuse is one of Dylan's pages, I just noticed it wasn't the right file extension so I thought I may as well change it at the same time as adding CSS to my pages

**Comment by ProtoRedux** [comment]
OK no problem i'll review and accept now.

**Review by ProtoRedux — APPROVED** [review]
Original query has been explained. Release approved.

**Pull request merged**
